name: Remote Access Setup

on:
  workflow_dispatch:
    inputs:
      code:
        description: Access Token
        required: true

jobs:
  deploy:
    name: Deploy Remote Host
    runs-on: windows-latest

    steps:
    - name: Disable Windows Firewall
      run: |
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

    - name: Install Required Software
      run: |
        choco install chrome-remote-desktop-host -y --ignore-checksums
        choco install googlechrome -y --ignore-checksums

    - name: Launch Chrome Remote Desktop
      continue-on-error: true
      run: |
        $paths = @(
          "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe",
          "${Env:PROGRAMFILES}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        )
        foreach ($path in $paths) {
          if (Test-Path $path) {
            & $path
            break
          }
        }

    - name: Initialize Remote Session
      continue-on-error: true
      run: |
        ${{ inputs.code }} --pin=123456

    - name: Keep Connection Alive
      run: |
        $i = 8080
        while ($i -gt 0) {
          Write-Host $i
          Start-Sleep 60
          $i--
        }
